### ISSUE TITLE
Find, Test and Choose a Mongo Web Admin UI in order to allow data extraction.

### ISSUE THREAD

**Issue by jonasdacruz** [konstellation-io/kre#288]
- https://github.com/mrvautin/adminMongo
- https://github.com/mongo-express/mongo-express
- https://github.com/bobthecow/genghis

**Comment by danielchg** [comment]
- AdminMongo: 
  - Docker image: YES
  - Config via ENV vars: YES
  - Restrict access: NO
  - Export CSV: NO

- Mongo Express:
  - Docker image: YES
  - Config ENV vars: YES
  - Restric access: YES
  - Export CSV: YES

- Genghis:
  - Docker image: YES (but not offical)
  - Config ENV vars: NO
  - Restrict access: NO
  - Export CSV: NO

**Conclusions:** the mongoExpress fit better for our goal, because allow to grant readonly access to a MongoDB database and allow to export as a .CSV or JSON the content of a collection.
